services:
  python:
    build:
      context: ./ai-backend
    restart: unless-stopped
    container_name: python
    mem_limit: 2g
    volumes:
      - ./ai-backend:/app
    environment:
      - HF_HOME=/app/.cache/huggingface
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgis/postgis:15-3.4-alpine
    restart: unless-stopped
    container_name: drizzle_db
    mem_limit: 512m
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laporan_db
    ports:
      - "5555:5432"