services:
  python:
    build:
      context: ./ai-backend
    restart: unless-stopped
    volumes:
      - ./ai-backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: pgvector/pgvector:0.8.5-pg18-trixie
    restart: unless-stopped
    container_name: drizzle_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laporan_db
    ports:
      - "5555:5432"