"use client";
import { FormEvent, useEffect, useState } from "react";

type District = { id: string; name: string; code: string };
type User = { id: string; name: string; email: string; role: string; districtIds: string[] };

export default function ManagementPage() {
  const [districts, setDistricts] = useState<District[]>([]); const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState("");
  const load = () => fetch("/api/admin/management").then((response) => response.json()).then((data) => { setDistricts(data.districts ?? []); setUsers(data.users ?? []); }).catch(() => setError("Data manajemen tidak dapat dimuat."));
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>, kind: "district" | "user") { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/management", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, ...Object.fromEntries(form) }) }); if (!response.ok) setError((await response.json()).error ?? "Gagal menyimpan data."); else { event.currentTarget.reset(); setError(""); load(); } }
  return <main style={{ maxWidth: 1120, margin: "0 auto", padding: "42px 24px", fontFamily: "var(--font-body)" }}><a href="/dashboard">← Dashboard</a><h1>Manajemen wilayah & akun</h1><p>Daftarkan kecamatan, admin kecamatan, dan OPD pelaksana.</p>{error && <p style={{ color: "#c62828" }}>{error}</p>}<section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: 20 }}><form onSubmit={(event) => submit(event, "district")}><h2>Tambah kecamatan</h2><input name="name" placeholder="Nama kecamatan" required /><input name="code" placeholder="Kode, mis. SUKAMAJU" required /><button>Tambah kecamatan</button></form><form onSubmit={(event) => submit(event, "user")}><h2>Tambah akun pelaksana</h2><input name="name" placeholder="Nama lengkap" required /><input name="email" type="email" placeholder="email@instansi.go.id" required /><input name="password" type="password" minLength={8} placeholder="Password minimal 8 karakter" required /><select name="role" required defaultValue=""><option value="" disabled>Pilih peran</option><option value="CAMAT">Admin kecamatan</option><option value="OPD">OPD pelaksana</option></select><select name="districtId" required defaultValue=""><option value="" disabled>Pilih kecamatan</option>{districts.map((district) => <option key={district.id} value={district.id}>{district.name}</option>)}</select><button>Tambah akun</button></form></section><section><h2>Kecamatan</h2><ul>{districts.map((district) => <li key={district.id}>{district.name} · {district.code}</li>)}</ul><h2>Pengguna</h2><ul>{users.map((user) => <li key={user.id}>{user.name} — {user.role} — {user.email}</li>)}</ul></section><style jsx>{`form{display:grid;gap:10px;padding:22px;border:1px solid #d9e2df;border-radius:8px;background:#fff}input,select,button{padding:11px;font:inherit}button{border:0;background:#0b2b4b;color:#fff;cursor:pointer}h1{margin:18px 0 8px}h2{margin:28px 0 12px}`}</style></main>;
}
