"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import styles from "./report-handler.module.css";

type History = { status: string; note: string; at: string; actor: string };
type Report = { code: string; category: string; severity: string; description: string; contactPhone: string; latitude: number; longitude: number; priority: string; status: string; assignedTo: string | null; createdAt: string; history: History[] };
const statusOptions = ["baru", "diverifikasi", "diproses", "selesai", "ditolak"];

export default function ReportHandler({ code }: { code: string }) {
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { fetch(`/api/admin/reports/${encodeURIComponent(code)}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setReport(data); }).catch((reason) => setError(reason.message)); }, [code]);
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/admin/reports/${encodeURIComponent(code)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: form.get("status"), assignedTo: form.get("assignedTo"), note: form.get("note") }) }); const data = await response.json(); setPending(false); if (!response.ok) setError(data.error); else { setReport(data); (event.currentTarget.elements.namedItem("note") as HTMLTextAreaElement).value = ""; } }
  if (error && !report) return <main className={styles.page}><Link href="/dashboard">← Dashboard</Link><h1>{error}</h1></main>;
  if (!report) return <main className={styles.page}>Memuat laporan…</main>;
  return <main className={styles.page}><header><Link href="/dashboard">← Kembali ke dashboard</Link><Link href={`/status/${report.code}`} target="_blank">Lihat sebagai warga ↗</Link></header><section className={styles.head}><div><p>PENANGANAN LAPORAN</p><h1>{report.code}</h1><span>{report.category} · Prioritas {report.priority}</span></div><strong>{report.status}</strong></section><section className={styles.grid}><article className={styles.detail}><p>DETAIL KEJADIAN</p><h2>{report.description}</h2><dl><div><dt>Dikirim</dt><dd>{new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeStyle: "short" }).format(new Date(report.createdAt))}</dd></div><div><dt>Kontak warga</dt><dd>{report.contactPhone}</dd></div><div><dt>Lokasi</dt><dd><a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${report.latitude}&mlon=${report.longitude}#map=18/${report.latitude}/${report.longitude}`}>{report.latitude.toFixed(5)}, {report.longitude.toFixed(5)} ↗</a></dd></div><div><dt>Petugas</dt><dd>{report.assignedTo ?? "Belum ditugaskan"}</dd></div></dl></article><article className={styles.action}><p>PERBARUI PENANGANAN</p><form onSubmit={update}><label>Status<select name="status" defaultValue={report.status} key={report.status}>{statusOptions.map((status) => <option key={status}>{status}</option>)}</select></label><label>Petugas / regu<input name="assignedTo" defaultValue={report.assignedTo ?? ""} placeholder="Contoh: Tim Infrastruktur 01" /></label><label>Catatan untuk warga<textarea name="note" required minLength={5} rows={4} placeholder="Jelaskan tindakan atau perkembangan terbaru…" /></label>{error && <div role="alert">{error}</div>}<button disabled={pending}>{pending ? "Menyimpan…" : "Simpan pembaruan"}</button></form></article><article className={styles.history}><p>RIWAYAT AKTIVITAS</p>{[...report.history].reverse().map((item, index) => <div key={`${item.at}-${index}`}><i /><span><b>{item.status}</b><small>{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.at))} · {item.actor}</small><p>{item.note}</p></span></div>)}</article></section></main>;
}
